
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbtk = new javax.swing.JTextField();
        tbpk = new javax.swing.JTextField();
        tblk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnbalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tbsisi = new javax.swing.JTextField();
        btnkubus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tbjari = new javax.swing.JTextField();
        btnbola = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Masukkan Tinggi :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Masukkan panjang :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(19, 21, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Masukkan lebar :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 60, 100, 30);
        jPanel1.add(tbtk);
        tbtk.setBounds(140, 100, 120, 30);
        jPanel1.add(tbpk);
        tbpk.setBounds(140, 20, 120, 30);
        jPanel1.add(tblk);
        tblk.setBounds(140, 60, 120, 30);

        jLabel5.setText("CM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 110, 34, 14);

        jLabel6.setText("CM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 30, 20, 14);

        jLabel7.setText("CM");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 70, 34, 14);

        btnbalok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbalok.setText("Hitung");
        btnbalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbalokActionPerformed(evt);
            }
        });
        jPanel1.add(btnbalok);
        btnbalok.setBounds(140, 150, 90, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Masukkan panjang sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(43, 29, 140, 30);
        jPanel2.add(tbsisi);
        tbsisi.setBounds(40, 60, 100, 30);

        btnkubus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnkubus.setText("Volume");
        btnkubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkubusActionPerformed(evt);
            }
        });
        jPanel2.add(btnkubus);
        btnkubus.setBounds(40, 110, 90, 30);

        jLabel9.setText("CM");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(150, 70, 34, 14);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Masukkan panjang jari-jari");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(39, 31, 160, 20);
        jPanel4.add(tbjari);
        tbjari.setBounds(40, 60, 100, 30);

        btnbola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbola.setText("Volume");
        btnbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbolaActionPerformed(evt);
            }
        });
        jPanel4.add(btnbola);
        btnbola.setBounds(40, 110, 90, 30);

        jLabel11.setText("Cm");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(150, 70, 40, 14);

        jTabbedPane1.addTab("Bola", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 400, 250);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 0, 270, 30);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbalokActionPerformed
        int panjang,lebar,tinggi;
        panjang=Integer.parseInt(tbpk.getText());
        lebar=Integer.parseInt(tblk.getText());
        tinggi=Integer.parseInt(tbtk.getText());;
        int hasil=panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok adalah : "+hasil,"Luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbalokActionPerformed

    private void btnkubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkubusActionPerformed
    int sisi;
    sisi=Integer.parseInt(tbsisi.getText());
    int hasil=sisi*sisi*sisi;
    
    try{
        JOptionPane.showMessageDialog(null,"Luas Permukaan kubus adalah = "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE); 
    }catch(Exception e) {
        JOptionPane.showMessageDialog(null,"Error"+ e,"Gagal",JOptionPane.WARNING_MESSAGE);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkubusActionPerformed

    private void btnbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbolaActionPerformed
        float jari;
        jari=Integer.parseInt(tbjari.getText());
        float hasil=(float) (4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola adalah = "+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbalok;
    private javax.swing.JButton btnbola;
    private javax.swing.JButton btnkubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tbjari;
    private javax.swing.JTextField tblk;
    private javax.swing.JTextField tbpk;
    private javax.swing.JTextField tbsisi;
    private javax.swing.JTextField tbtk;
    // End of variables declaration//GEN-END:variables
}
